spring:
  application:
    name: employee-microservice-dataset

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8097
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream  

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false